/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        nb: {
          black: '#1A1A1A',
          white: '#FAFAF5',
          cream: '#FFF8E7',
          yellow: '#FFD700',
          'yellow-light': '#FFF0AA',
          blue: '#0066FF',
          'blue-light': '#D6EAFF',
          green: '#00CC66',
          'green-light': '#D4F5E2',
          pink: '#FF3366',
          'pink-light': '#FFD6E0',
          orange: '#FF6B00',
          'orange-light': '#FFE0C2',
          red: '#E53E3E',
          'red-light': '#FED7D7',
          gray: {
            50: '#FAFAF5',
            100: '#F0EDE4',
            200: '#E2DFD6',
            300: '#C8C4BA',
            400: '#A8A49A',
            500: '#88847A',
            600: '#68645A',
            700: '#484440',
            800: '#2E2A26',
            900: '#1A1A1A',
          },
        },
        dark: {
          bg: '#121212',
          surface: '#1E1E1E',
          elevated: '#2A2A2A',
          border: '#3A3A3A',
          text: '#E0E0E0',
          muted: '#888888',
        },
      },
      fontFamily: {
        display: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.8125rem', { lineHeight: '1.25rem' }],
        base: ['0.875rem', { lineHeight: '1.375rem' }],
        lg: ['1rem', { lineHeight: '1.5rem' }],
        xl: ['1.125rem', { lineHeight: '1.625rem' }],
        '2xl': ['1.375rem', { lineHeight: '1.75rem' }],
        '3xl': ['1.75rem', { lineHeight: '2.125rem' }],
      },
      boxShadow: {
        'nb-sm': '2px 2px 0px 0px #1A1A1A',
        nb: '4px 4px 0px 0px #1A1A1A',
        'nb-lg': '6px 6px 0px 0px #1A1A1A',
        'nb-xl': '8px 8px 0px 0px #1A1A1A',
        'nb-dark-sm': '2px 2px 0px 0px #000000',
        'nb-dark': '4px 4px 0px 0px #000000',
        'nb-dark-lg': '6px 6px 0px 0px #000000',
      },
      borderWidth: {
        3: '3px',
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        14: '56px',
        16: '64px',
      },
      animation: {
        'slide-in-right': 'slideInRight 0.2s ease-out',
        'slide-in-left': 'slideInLeft 0.2s ease-out',
        'fade-in': 'fadeIn 0.15s ease-out',
        'bounce-in': 'bounceIn 0.3s ease-out',
        'toast-in': 'toastIn 0.3s ease-out',
      },
      keyframes: {
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: 0 },
          '100%': { transform: 'translateX(0)', opacity: 1 },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: 0 },
          '100%': { transform: 'translateX(0)', opacity: 1 },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.9)', opacity: 0 },
          '50%': { transform: 'scale(1.02)' },
          '100%': { transform: 'scale(1)', opacity: 1 },
        },
        toastIn: {
          '0%': { transform: 'translateY(-16px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
      },
    },
  },
  plugins: [],
};
