/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    extend: {
      colors: {
        nc: {
          black: 'rgb(var(--nc-black) / <alpha-value>)',
          deep: 'rgb(var(--nc-deep) / <alpha-value>)',
          surface: 'rgb(var(--nc-surface) / <alpha-value>)',
          elevated: 'rgb(var(--nc-elevated) / <alpha-value>)',
          border: 'rgb(var(--nc-border) / <alpha-value>)',
          'border-bright': 'rgb(var(--nc-border-bright) / <alpha-value>)',
          red: 'rgb(var(--nc-red) / <alpha-value>)',
          'red-glow': 'rgb(var(--nc-red) / 0.3)',
          'red-dim': 'rgb(var(--nc-red) / 0.1)',
          green: 'rgb(var(--nc-green) / <alpha-value>)',
          'green-glow': 'rgb(var(--nc-green) / 0.3)',
          'green-dim': 'rgb(var(--nc-green) / 0.1)',
          cyan: 'rgb(var(--nc-cyan) / <alpha-value>)',
          'cyan-glow': 'rgb(var(--nc-cyan) / 0.3)',
          'cyan-dim': 'rgb(var(--nc-cyan) / 0.1)',
          yellow: 'rgb(var(--nc-yellow) / <alpha-value>)',
          'yellow-glow': 'rgb(var(--nc-yellow) / 0.3)',
          'yellow-dim': 'rgb(var(--nc-yellow) / 0.1)',
          magenta: 'rgb(var(--nc-magenta) / <alpha-value>)',
          'magenta-glow': 'rgb(var(--nc-magenta) / 0.3)',
          indigo: 'rgb(var(--nc-indigo) / <alpha-value>)',
          success: 'rgb(var(--nc-success) / <alpha-value>)',
          error: 'rgb(var(--nc-error) / <alpha-value>)',
          warning: 'rgb(var(--nc-warning) / <alpha-value>)',
          info: 'rgb(var(--nc-info) / <alpha-value>)',
          text: 'rgb(var(--nc-text) / <alpha-value>)',
          'text-bright': 'rgb(var(--nc-text-bright) / <alpha-value>)',
          muted: 'rgb(var(--nc-muted) / <alpha-value>)',
          panel: 'rgb(var(--nc-panel) / <alpha-value>)',
        },
      },
      fontFamily: {
        display: 'var(--nc-font-display)',
        body: 'var(--nc-font-body)',
        mono: 'var(--nc-font-mono)',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.8125rem', { lineHeight: '1.25rem' }],
        base: ['0.875rem', { lineHeight: '1.375rem' }],
        lg: ['1rem', { lineHeight: '1.5rem' }],
        xl: ['1.125rem', { lineHeight: '1.625rem' }],
        '2xl': ['1.375rem', { lineHeight: '1.75rem' }],
        '3xl': ['1.75rem', { lineHeight: '2.125rem' }],
      },
      boxShadow: {
        'nc-cyan': 'none',
        'nc-red': 'none',
        'nc-green': 'none',
        'nc-yellow': 'none',
        'nc-magenta': 'none',
        'nc-inset': 'none',
        'nc-panel': '0 4px 24px rgba(0, 0, 0, 0.5)',
      },
      borderWidth: {
        1: '1px',
        3: '3px',
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        14: '56px',
        16: '64px',
      },
      animation: {
        'slide-in-right': 'slideInRight 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-left': 'slideInLeft 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-in': 'fadeIn 0.2s ease-out',
        'bounce-in': 'bounceIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'toast-in': 'toastIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'scanline': 'scanlineMove 8s linear infinite',
        'flicker': 'flicker 4s linear infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'glitch-skew': 'glitchSkew 4s linear infinite',
        'border-glow': 'borderGlow 4s linear infinite',
        'text-glitch': 'textGlitch 3s linear infinite',
      },
      keyframes: {
        slideInRight: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '50%': { transform: 'scale(1.01)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        toastIn: {
          '0%': { transform: 'translateY(-16px) translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0) translateX(0)', opacity: '1' },
        },
        scanlineMove: {
          '0%': { top: '-5%' },
          '100%': { top: '105%' },
        },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '41%': { opacity: '1' },
          '42%': { opacity: '0.8' },
          '43%': { opacity: '1' },
          '45%': { opacity: '0.3' },
          '46%': { opacity: '1' },
          '50%': { opacity: '1' },
          '51%': { opacity: '0.6' },
          '52%': { opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { opacity: '0.5' },
          '50%': { opacity: '1' },
        },
        glitchSkew: {
          '0%, 100%': { transform: 'skewX(0deg)' },
          '20%': { transform: 'skewX(-2deg)' },
          '40%': { transform: 'skewX(1deg)' },
          '60%': { transform: 'skewX(-1deg)' },
          '80%': { transform: 'skewX(0.5deg)' },
        },
        borderGlow: {
          '0%': { borderColor: 'rgb(var(--nc-cyan))', boxShadow: '0 0 8px rgb(var(--nc-cyan) / 0.4)' },
          '25%': { borderColor: 'rgb(var(--nc-magenta))', boxShadow: '0 0 8px rgb(var(--nc-magenta) / 0.4)' },
          '50%': { borderColor: 'rgb(var(--nc-yellow))', boxShadow: '0 0 8px rgb(var(--nc-yellow) / 0.4)' },
          '75%': { borderColor: 'rgb(var(--nc-red))', boxShadow: '0 0 8px rgb(var(--nc-red) / 0.4)' },
          '100%': { borderColor: 'rgb(var(--nc-cyan))', boxShadow: '0 0 8px rgb(var(--nc-cyan) / 0.4)' },
        },
        textGlitch: {
          '0%, 100%': { textShadow: '-1px 0 rgb(var(--nc-cyan)), 1px 0 rgb(var(--nc-red))' },
          '25%': { textShadow: '1px 0 rgb(var(--nc-cyan)), -1px 0 rgb(var(--nc-red))' },
          '50%': { textShadow: '-1px 1px rgb(var(--nc-cyan)), 1px -1px rgb(var(--nc-red))' },
          '75%': { textShadow: '1px -1px rgb(var(--nc-cyan)), -1px 1px rgb(var(--nc-red))' },
        },
      },
    },
  },
  plugins: [],
};
